### ISSUE TITLE
Changes Not Updating

### ISSUE THREAD

**Issue by pricemi115** [pricemi115/homebridge-grumptech-volmon#50]
When volumes come and go, the change is not reflected in the Home app after updating to the new HomeKit back end.
Also not showing up in the Home+, Eve Home, or ControlerForHome apps

Incidentally when updating, I lost the temp, RH, and AirQ sensors on the EveRoom device when updating. Removing an re-adding the device resolved the issue.

Removing the bridge and re-adding will allow existing volumes to become part of HomeKit, but when they disappear, they cannot be re-added.

Also lost the volumes on a RasPi when updating the HomeKit back end.

Hopefully this will be resolved in a future update.

Workaround:
Have the volumes you care about mounted when adding the plugin (best done as a child-bridge). Then keep the Purge switch off. A future update will use the charging status to indicate a mounted volume using the "charging" attribute

**Comment by pricemi115** [comment]
FWIW - Homebridge is correctly showing the volumes as they come and go.

**Comment by podfeet** [comment]
Does this mean the brokenness is no longer broken?

**Comment by pricemi115** [comment]
@podfeet - No. Definitely "broken" from my definition. While plugin itself is correctly adding and removing accessories  "on the fly" as volumes come and go and the do show up in the Homebridge web view , once removed, the accessories never show back up in HomeKit. Also, if a _new_ volume is mounted after adding the platform accessory to HomeKit, it also will not show up.

**Comment by pricemi115** [comment]
Seems to not be `broken` after all, @podfeet  🎉
There were several accessories _stuck_ in the `Default Room`. Once I cleared these out by assigning all these _lost_ accessories to the correct room, the dynamic accessories came into the correct room once again.

**Comment by podfeet** [comment]
Fantastic!!!
